apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: producer-statefulset
  labels:
    app: producer-statefulset
  namespace: {{ .Values.namespace | quote }}
spec:
  serviceName: producer-statefulset-lb
  replicas: 1
  selector:
    matchLabels:
      app: producer-statefulset
  template:
    metadata:
      labels:
        app: producer-statefulset
    spec:
      containers:
        - name: producer-container
          image: {{ .Values.cardanoNode.image | quote }}
          command: ["cardanopy",
                    "run",
                    "--sub",
                    {{ print "_BP_ENABLED=" .Values.cardanoNode.bpEnabled | quote }},
                    "--sub",
                    "_NAME=$(CARDANO_NODE_NAME)",
                    {{ .Values.cardanoNode.appDir | quote }}]
          livenessProbe:
            exec:
              command: ["cardanopy",
                        "healthcheck",
                        "--timeout",
                        60,
                        {{ .Values.cardanoNode.appDir | quote }}]
            initialDelaySeconds: 60
            periodSeconds: 60
          env:
            - name: CARDANO_NETWORK
              value: {{ .Values.cardanoNode.network | quote }}
            - name: CARDANO_NODE_SOCKET_PATH
              value: {{ .Values.cardanoNode.socketPath | quote }}
            - name: CARDANO_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 3001
            - containerPort: 12798
            - containerPort: 12788
          volumeMounts:
            - mountPath: {{ .Values.cardanoNode.homeDir | quote }}
              name: producer-pvc
      initContainers:
        - name: init-producer-container
          image: {{ .Values.cardanoNode.image | quote }}
          command: [ "cardanopy",
                     "create",
                     "--quite",
                     "--template",
                     "bp-k8s",
                     "--network",
                     {{ .Values.cardanoNode.network | quote }},
                     {{ .Values.cardanoNode.appDir | quote }} ]
          volumeMounts:
            - mountPath: {{ .Values.cardanoNode.homeDir | quote }}
              name: producer-pvc
  volumeClaimTemplates:
    - metadata:
        name: producer-pvc
        namespace: {{ .Values.namespace | quote }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
