apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: producer-statefulset
  labels:
    app: producer-statefulset
  namespace: {{ .Values.namespace | quote }}
spec:
  serviceName: producer-statefulset-lb
  replicas: 1
  selector:
    matchLabels:
      app: producer-statefulset
  template:
    metadata:
      labels:
        app: producer-statefulset
    spec:
      containers:
        - name: producer-container
          image: {{ .Values.cardanoNode.image | quote }}
          command: ["cardanopy",
                    "run",
                    "--sub",
                    {{ printf "_BP_ENABLED=%s" .Values.cardanoNode.bpEnabled | quote }},
                    {{ .Values.cardanoNode.appDir | quote }}]
          env:
            - name: CARDANO_NETWORK
              value: {{ .Values.cardanoNode.network | quote  }}
            - name: CARDANO_NODE_SOCKET_PATH
              value: {{ .Values.cardanoNode.socketPath | quote }}
          ports:
            - containerPort: 3001
            - containerPort: 12798
            - containerPort: 12788
          volumeMounts:
              - mountPath: {{ .Values.cardanoNode.appDir | quote  }}
                name: producer-pvc
      initContainers:
        - name: init-producer-container
          image: {{ .Values.cardanoNode.image | quote }}
          command: [ "cardanopy",
                     "create",
                     "--template",
                     "bp-k8s",
                     "--network",
                     {{ .Values.cardanoNode.network | quote  }},
                     {{ .Values.cardanoNode.appDir | quote }} ]
      nodeSelector:
        pool: default
  volumeClaimTemplates:
    - metadata:
        name: producer-pvc
        namespace: {{ .Values.namespace | quote }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
