apiVersion: v1
kind: Service
metadata:
  name: relay-backend
  namespace: {{ .Values.namespace | quote }}
spec:
  type: NodePort
  selector:
    app: relay-statefulset
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001