apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: relay-statefulset
  labels:
    app: relay-statefulset
  namespace: {{ .Values.namespace | quote }}
spec:
  serviceName: relay-statefulset-lb
  replicas: 2
  selector:
    matchLabels:
      app: relay-statefulset
  template:
    metadata:
      labels:
        app: relay-statefulset
    spec:
      containers:
        - name: relay-container
          image: {{ .Values.cardanoNode.image | quote }}
          command: ["cardanopy",
                    "run",
                    "--sub",
                    "_NAME=$(CARDANO_NODE_NAME)",
                    {{ .Values.cardanoNode.appDir | quote }}]
          livenessProbe:
            exec:
              command: [ "cardanopy",
                         "healthcheck",
                         "--timeout",
                         "5",
                         {{ .Values.cardanoNode.appDir | quote }}]
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 60
          env:
            - name: CARDANO_NETWORK
              value: {{ .Values.cardanoNode.network | quote }}
            - name: CARDANO_NODE_SOCKET_PATH
              value: {{ .Values.cardanoNode.socketPath | quote }}
            - name: CARDANO_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 3001
            - containerPort: 12798
            - containerPort: 12788
          volumeMounts:
            - mountPath: {{ .Values.cardanoNode.homeDir | quote }}
              name: relay-pvc
      initContainers:
        - name: init-producer-container
          image: {{ .Values.cardanoNode.image | quote }}
          command: [ "cardanopy",
                     "create",
                     "--quite",
                     "--template",
                     "relay-k8s",
                     "--network",
                     {{ .Values.cardanoNode.network | quote }},
                     {{ .Values.cardanoNode.appDir | quote }} ]
          volumeMounts:
            - mountPath: {{ .Values.cardanoNode.homeDir | quote }}
              name: relay-pvc
  volumeClaimTemplates:
    - metadata:
        name: relay-pvc
        namespace: {{ .Values.namespace | quote }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
