apiVersion: v1
kind: Service
metadata:
  name: relay-statefulset-ipv6-lb
  namespace: {{ .Values.namespace | quote }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.cardanoNode.relayIpv6 | quote }}
  selector:
    app: relay-statefulset
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001