apiVersion: v1
kind: Service
metadata:
  name: web-backend-deployment-lb
  namespace: {{ .Values.namespace | quote }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: web-backend-deployment
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080