apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web-deployment
  namespace: {{ .Values.namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-deployment
  template:
    metadata:
      labels:
        app: web-deployment
    spec:
      nodeSelector:
        pool: e2-pool
      containers:
        - name: container
          image: {{ .Values.CardanoPyWebBackend.image | quote }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: CARDANO_NETWORK
              value: {{ .Values.cardanoNode.network | quote }}