buildId: "45fa43b9-3c0c-48a0-9489-3f844b116841"
version: "0.1.9"
commitSha: "0538303cd618177232533144ac4e92c14ca86af5"
branchName: "master"
cardanoNode:
  image: "floydcraft/cardano-py-slim:0538303cd618177232533144ac4e92c14ca86af5"
  network: "testnet"
  homeDir: "/home/ada"
  appDir: "/home/ada/app"
  socketPath: "/home/ada/app/node.socket"
  databasePath: "/home/ada/app/db"
CardanoPyWebBackend:
    image: "floydcraft/cardano-py-web:94f20769f85404452d7689da4ec09ac20abf3d4a"