buildId: "09bd9a23-8431-42e2-ae2a-cc5e0199383f"
version: "0.1.7-dev27"
commitSha: "380b98b67371b7acdd9126454f743140b68dcad7"
branchName: "master"
cardanoNode:
  image: "floydcraft/cardano-py-slim:380b98b67371b7acdd9126454f743140b68dcad7"
  network: "testnet"
  homeDir: "/home/ada"
  appDir: "/home/ada/app"
  socketPath: "/home/ada/app/node.socket"
  databasePath: "/home/ada/app/db"
CardanoPyWebBackend:
    image: "floydcraft/cardano-py-web-backend:latest"