buildId: "f3e088f3-6248-488f-91db-acafa7da0ac2"
version: "0.1.7-dev22"
commitSha: "971d08ea7ea55426a1463328966d7c1c150c5f82"
branchName: "master"
cardanoNode:
  image: "floydcraft/cardano-py-slim:971d08ea7ea55426a1463328966d7c1c150c5f82"
  network: "testnet"
  homeDir: "/home/ada"
  appDir: "/home/ada/app"
  socketPath: "/home/ada/app/node.socket"
  databasePath: "/home/ada/app/db"
CardanoPyWebBackend:
    image: "floydcraft/cardano-py-web-backend:latest"