buildId: 89013e78-84ff-4135-9575-7da861e320b2
version: 0.1.7-dev15
commitSha: d4f654f587fe31a816970cc692e5a75899ac8c95
branchName: master
namespace: cardano-testnet
cardanoNode:
  image: "floydcraft/cardano-py-slim:d4f654f587fe31a816970cc692e5a75899ac8c95"
  network: "testnet"
  homeDir: "/home/ada"
  appDir: "/home/ada/app"
  socketPath: "/home/ada/app/node.socket"
  podOrdinal: 0
  targetPodOrdinal: 1
  bpEnabled: False
  databasePath: "/home/ada/app/db"
