buildId: "e9ab2e99-a7a9-4de3-88cd-bdc0ec1dac0b"
version: "0.1.7-dev17"
commitSha: "8c6dfc0ff06267750b8e787e1b3394df34ca15d9"
branchName: "master"
cardanoNode:
  image: "floydcraft/cardano-py-slim:8c6dfc0ff06267750b8e787e1b3394df34ca15d9"
  network: "testnet"
  homeDir: "/home/ada"
  appDir: "/home/ada/app"
  socketPath: "/home/ada/app/node.socket"
  bpEnabled: False
  databasePath: "/home/ada/app/db"
CardanoPyWebBackend:
    image: "floydcraft/cardano-py-web-backend:5191ee8fdc9b099451bbaa8d6287ef2ddc085ced"