buildId: "6bebb3a3-4aee-4ad4-9743-c7bc32e0e386"
version: "0.1.10-dev1"
commitSha: "76aa58953594538e2379d10bc04fbdcdbe87d851"
branchName: "master"
cardanoNode:
  image: "floydcraft/cardano-py-slim:76aa58953594538e2379d10bc04fbdcdbe87d851"
  network: "testnet"
  homeDir: "/home/ada"
  appDir: "/home/ada/app"
  socketPath: "/home/ada/app/node.socket"
  databasePath: "/home/ada/app/db"
CardanoPyWebBackend:
    image: "floydcraft/cardano-py-web:94f20769f85404452d7689da4ec09ac20abf3d4a"