buildId: "9c1bc1e6-f078-43a5-af65-87f3c96a2277"
version: "0.1.7-dev28"
commitSha: "3d4754640ac7dbd9e5fbf61570494a1b52c414a5"
branchName: "master"
cardanoNode:
  image: "floydcraft/cardano-py-slim:3d4754640ac7dbd9e5fbf61570494a1b52c414a5"
  network: "testnet"
  homeDir: "/home/ada"
  appDir: "/home/ada/app"
  socketPath: "/home/ada/app/node.socket"
  databasePath: "/home/ada/app/db"
CardanoPyWebBackend:
    image: "floydcraft/cardano-py-web:latest"