buildId: "f61c4d28-0723-4c8c-a7c5-5f7a0ed4068c"
version: "0.1.9-dev1"
commitSha: "fca45d2b03c1172d5ae6a62440b1a16298618d91"
branchName: "master"
cardanoNode:
  image: "floydcraft/cardano-py-slim:fca45d2b03c1172d5ae6a62440b1a16298618d91"
  network: "testnet"
  homeDir: "/home/ada"
  appDir: "/home/ada/app"
  socketPath: "/home/ada/app/node.socket"
  databasePath: "/home/ada/app/db"
CardanoPyWebBackend:
    image: "floydcraft/cardano-py-web:94f20769f85404452d7689da4ec09ac20abf3d4a"