apiVersion: cardanopy.node.config/v1
substitutions:
  _BP_ENABLED: False
name: "relay-k8s"
network: "testnet"
config: "config/config.json"
databasePath: "storage/db"
socketPath: "storage/node.socket"
topologyPath: "config/topology.json"
hostAddr: "0.0.0.0"
port: 3001
blockProducer:
  enabled: $_BP_ENABLED
  shelleyKesKey: "bp/kes.skey"
  shelleyVrfKey: "bp/vrf.skey"
  shelleyOperationalCertificate: "bp/node.cert"
topology:
  Producers:
    - addr: "relay-statefulset-lb.cardano-testnet.svc.cluster.local"
      port: 3001
      valency: 2
docker:
  image: "floydcraft/cardano-py-slim:latest"
  volumes:
    - "storage:storage"
k8s:
  namespace: "cardano-testnet"


